name: Deploy to Hugging Face Space

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Git LFS and pull LFS objects
        run: |
          git lfs install
          git lfs pull

      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://huggingface.co/spaces/gym-vision/gymvision-space.git
          git config user.email "ci@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.HF_TOKEN }}" push -f hf HEAD:main
